function main(modelfile)
%% function main(modelfile)
% Main entry point to the SQGMU solver.
%
% Arguments:
%  - [optional] modelfile: a .MAT file containing a variable "model", as
%   returned by set_model(). This is useful e.g. with compiled M-code, see
%   compile/compile.m for more information.
%
% Written by P. Derian - 2016.
% Modified by P. Derian - 2017-03-10: enabled loading models.

% start
fprintf(1, '*** <SQGMU-2.0> ***\n');

% NB: this initialization is skipped in compile mode
if ~isdeployed
    init;
end

% load a model previously generated by set_model() from a .mat.
if 1==nargin
    fprintf(1, '\nLoading model from %s\n\n', modelfile);
    load(modelfile, 'model');
else
% set new model
    fprintf(1, '\nCreating model from set_model()\n\n');
    model = set_model();
end;

% Generating initial buoyancy
[fft_buoy_init, model] = fct_buoyancy_init_ens(model);

% Advection
[fft_buoy_final, model] = fct_fft_advection_sto(model, fft_buoy_init);

% Done
fprintf(1, '*** </SQGMU-2.0> ***\n');
end