function [epsi2,spectrum,name_plot] = fct_plot_epsilon_k(model,...
                fft_b_adv_part,day)
%                fft_b_adv_part,int_epsilon_dt_m_1,day)
% This function creates some plot online and save it
%

%% Get paramters

% Grid
x = model.grid.x;
y = model.grid.y;
My = model.grid.MX(2);

% Other parameters
taille_police = 12;
id_part=1;
type_data = model.type_data;
folder_simu = model.folder.folder_simu;
plot_moments = model.advection.plot_moments;
%plot_epsilon_k = model.advection.plot_epsilon_k;
map = model.folder.colormap;


%% Dissipation by scale
X0=[7 1];
close(figure(8))
figure8=figure(8);

widthtemp = 12;
heighttemp = 6;
set(figure8,'Units','inches', ...
    'Position',[X0(1) X0(2) widthtemp heighttemp], ...
    'PaperPositionMode','auto');
model.sigma.km_LS = model.sigma.km_LS(id_part);
epsi2 = fct_epsilon_k( model,fft_b_adv_part(:,:,:,id_part),day);
%    int_epsilon_dt_m_1,'b');
set(gca,'XGrid','on','XTickMode','manual');
width = 4;
height = 3;
set(figure8,'Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
set(gca,'YGrid','on')

set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'FontName','Times')
ylabel('$\epsilon(\kappa)$',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',taille_police,...
    'FontName','Times')
xlabel('$\kappa \bigl ( rad.m^{-1} \bigr )$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',taille_police,...
    'interpreter','latex',...
    'FontName','Times')
title({'Dissipation by scale' ...
    '\hspace{0.5cm} one realization'},...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
drawnow
eval( ['print -depsc ' folder_simu '/Epsilon_k/' day '.eps']);


